import FirstProof2Scalar.Problem2Scalar
import FirstProof2Scalar.Problem2Logical
import FirstProof2Scalar.Problem2FiniteFourier
import FirstProof2Scalar.Problem2VectorFourier
import FirstProof2Scalar.Problem2MatrixFourier
